name: Build and Push Docker Image

on:
  push:
    branches: [ command ] # 只在主分支推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # 检出代码

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get Commit SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wufly632/cargo-generate:${{ steps.sha.outputs.short_sha }} # 替换为你的镜像标签
